version: '3.8'

services:
  ciclica-web:
    image: ciclica-web:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - MP_PLAN_AMOUNT=${MP_PLAN_AMOUNT}
      - MP_CURRENCY=${MP_CURRENCY}
      - MP_WEBHOOK_SECRET=${MP_WEBHOOK_SECRET}
    networks:
      - flip
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.ciclica-app.rule=Host(`app.ciclica.pro`)
        - traefik.http.routers.ciclica-app.entrypoints=websecure
        - traefik.http.routers.ciclica-app.tls.certresolver=letsencrypt
        - traefik.http.services.ciclica-app.loadbalancer.server.port=3000
        - traefik.docker.network=flip

networks:
  flip:
    external: true
